datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    password: admin
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
  jpa:
   hibernate:
      ddl-auto: update
   properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
   show-sql: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
 
 microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PaymentService/Payment/message
  customer-service:
    endpoints:
      endpoint:
        uri: http://CustomerService/Customer/message
  product-service:
    endpoints:
      endpoint:
        uri: http://ProductService/Product/Product
